docroot/profiles/custom/stanford_profile/config/sync/core.base_field_override.node.datatables_data.title.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_form_display.node.datatables_data.default.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.datatables_data.default.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.datatables_data.teaser.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.datatables_data.body.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.datatables_data.su_casbs_file_data.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.datatables_data.su_casbs_long_data.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_file_data.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_long_data.yml
docroot/profiles/custom/stanford_profile/config/sync/node.type.datatables_data.yml
docroot/profiles/custom/stanford_profile/config/sync/rabbit_hole.behavior_settings.node_type_datatables_data.yml

- Added datatables_data content type and fields
- 3-15-23
- non-urgent

Added datatables_data content type and fields

---

docroot/profiles/custom/stanford_profile/config/sync/core.base_field_override.node.casbs_book.title.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_form_display.node.casbs_book.default.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.casbs_book.default.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.casbs_book.teaser.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.body.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_author_links.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_author_name.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_book_cover.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_book_id.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_book_publish_year.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_book_publisher.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_book_publisher_loc.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_book_title.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_author_links.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_author_name.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_book_cover.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_book_id.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_book_publish_year.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_book_publisher.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_book_publisher_loc.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_book_title.yml
docroot/profiles/custom/stanford_profile/config/sync/jsonapi.settings.yml
docroot/profiles/custom/stanford_profile/config/sync/node.type.casbs_book.yml
docroot/profiles/custom/stanford_profile/config/sync/node.type.stanford_person.yml
docroot/profiles/custom/stanford_profile/config/sync/rabbit_hole.behavior_settings.node_type_casbs_book.yml
docroot/profiles/custom/stanford_profile/config/sync/simplesamlphp_auth.settings.yml
docroot/profiles/custom/stanford_profile/config/sync/user.role.site_builder.yml
docroot/profiles/custom/stanford_profile/config/sync/user.role.site_developer.yml
docroot/profiles/custom/stanford_profile/config/sync/user.role.site_editor.yml
docroot/profiles/custom/stanford_profile/config/sync/user.role.site_manager.yml

- adding custom data type
CASBS BOOK
su_casbs_author_name
su_casbs_author_links
su_casbs_book_cover
su_casbs_book_title
su_casbs_book_id
su_casbs_book_publisher
su_casbs_book_publisher_loc
su_casbs_book_publish_year
- 3-17-2023
- non-urgent

adding custom data type casbs casbs_book

---

docroot/profiles/custom/stanford_profile/config/sync/core.entity_form_display.node.stanford_person.default.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.stanford_person.default.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.stanford_person.search_indexing.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.stanford_person.stanford_card.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.stanford_person.teaser.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.stanford_person.su_casbs_faculty_fellow_year.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.stanford_person.su_casbs_person_type.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.stanford_person.su_casbs_profile_picture.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_faculty_fellow_year.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_fellowship_year.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_person_type.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_practitioner_year.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_ra_year.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_visiting_scholar_year.yml
docroot/profiles/custom/stanford_profile/config/sync/simplesamlphp_auth.settings.yml

- make years multi-value, remove field su_casbs_fellowship_association, change person su_faculty_fellow_year to correct taxonomy
3-27-2023
non Urgent

AGAIN make years multi-value, remove field su_casbs_fellowship_association, change person su_faculty_fellow_year to correct taxonomy

---

docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.casbs_book.full.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.stanford_page.default.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.stanford_person.default.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_author_name.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_book_publish_year.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_book_publisher.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_book_publisher_loc.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_book_title.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_book_id.yml
docroot/profiles/custom/stanford_profile/config/sync/filter.format.no_processing.yml
docroot/profiles/custom/stanford_profile/config/sync/node.type.casbs_book.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_board.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_faculty_fellows_and_research_affiliates.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_fellows.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_visiting_scholars.yml

Change and Add some views
4-7-2023
non-urgent

change and add some views

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_staff.yml

- change staff and board views to show all instead of 5
4-7-2023
- non-Urgent

change staff and board views to show all instead of 5

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_board.yml

- Tchange view to sort on mailcode order for arbitrary board member order
- 4-7-2023
- Non-urgent

change view to sort on Mailcode weight for board members

---

docroot/profiles/custom/stanford_profile/config/sync/core.entity_form_display.node.stanford_person.default.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.stanford_person.default.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.stanford_person.search_indexing.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.stanford_person.stanford_card.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.stanford_person.teaser.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_board.yml

- try to remove fellowship_year again, add mailcode sort to casbs board
- 4-10-2023
non-urgent

try to remove fellowship_year again, add mailcode sort to casbs board

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_board_of_directors.yml

- make newcasbs bord of directors view because can't modify existing views
- 4-10-2023
- non-urgent

make newcasbs bord of directors view because can't modify existing views

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_staff.yml

- add fields to casbs_staff view
- 4-10-2023
non-urgent

add fields to casbs_staff view

---

docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_person_type.yml

- changing su_casbs_person_type to be multiple values
- 4-10-2023
- non-urgent

changing su_casbs_person_type to be multiple values

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_staff.yml

- modify casbs_staff view
4-12-2023
non-urgent

modify casbs_staff view

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_board_of_directors.yml

- changed order of board view
- 4-13-2023
- non-urgent

changed order of board view

---

docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.stanford_person.default.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view._book_mosaic.yml

READY FOR REVIEW
add book mosaic and change some views
4-14-2023
non-urgent

add book mosaic and change some views

---

docroot/profiles/custom/stanford_profile/config/sync/core.entity_form_display.node.casbs_book.default.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.casbs_book.default.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.casbs_book.full.yml
docroot/profiles/custom/stanford_profile/config/sync/core.entity_view_display.node.casbs_book.teaser.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.casbs_book.su_casbs_recent_works.yml
docroot/profiles/custom/stanford_profile/config/sync/field.storage.node.su_casbs_recent_works.yml

[casbs_book recent works boolean
4-15-2023
non urgent

casbs_book recent works boolean

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_book_mosaic.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_recentworks.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_recentworks_mosaic.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_staff.yml

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

fix views book person recentworks

---

docroot/profiles/custom/stanford_profile/config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_board_of_directors.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_book_mosaic.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_fellows.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_visiting_scholars.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_recentworks.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_recentworks_mosaic.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_staff.yml

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

fix people and books views

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_recentworks_mosaic.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_staff.yml

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

fix custom sort staff view and recent works mosaic to 1 display

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_recentworks.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_recentworks_mosaic.yml

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

Add author name to recentworks and recentworks mosaic

---

docroot/profiles/custom/stanford_profile/config/sync/image.style.su_news_list.yml

- The news list display did not honor focal point, resulting in many decapitations. This fixes that.
- Launch
- Medium
1. Go to the news page
2. Look at "[Q&A with Yi-huah Jiang](https://stanfordcasbsdev.prod.acquia-sites.com/news/qa-yi-huah-jiang)"
- CAS-182
- cc: @brucedyoung 
- NOTE: This issue also exists on Core.

CAS-182: focal point on news

---

docroot/profiles/custom/stanford_profile/config/sync/editor.editor.stanford_html.yml

- The HTML format now access junky formatting from pretty much anywhere. This affects especially copy/pasted content from other sites (like the D7 site)
- Launch
- High
1. Go to a WYSIWYG
2. Throw in something awful
3. Scrub it with that nice button!
- CAS-185

CAS-185: Adding the remove formatting button

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_fellows.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_people_qa.yml

- Created a QA view that is sortable to look at Bruce's data on prod
- Adjusted the Stanford person view and Bruce's people views to use the data with contextual filtering
- ASAP
- Important, since looking at that data is what is blocking me from finishing the views
1. Go to /admin/casbs-people-qa
2. Look at data!
3. Or, try to use the casbs_person_type vocab to filter either bruce's views or our default views
- All the people pages
- CAS-180

CAS-180: qa view and people view update

---

docroot/profiles/custom/stanford_profile/config/sync/field.field.node.stanford_person.su_casbs_custom_order.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_fellows.yml

- Moved all of Bruce's views into a single place so they can inherit useful things from each other (and make the picking of views a little more streamlined in the UI)
- Added classes to views for styling
- Added a default number to the CASBS custom sort order so that re-ordering views does not require editing that field for everyone
- Added additional sort order where needed so that views could be used without custom order
- ASAP
- IMPORTANT
1. Try to use a list paragraph
2. Pick CASBS People
3. Enjoy how it is tidy (note: old views are still there for QA purposes)
- CASBS People pages
- CAS-180
- @brucedyoung 

CAS-180: More cleanup to views

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_board_of_directors.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_book_mosaic.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_faculty_fellows_and_research_affiliates.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_fellows.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_visiting_scholars.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_people_qa.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_recentworks.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_recentworks_mosaic.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_staff.yml

- Disable unused views
- Add classes to views for styling
- Make names human-readable
- Fix jump menu on Staff page
- AS soon as possible
- Super important
1. Check out the People pages, especially /people/staff
2. Notice Jump Menu works
3. Try adding a list paragraph, and notice the selections are now tidy
4. Go to the recent works page and notice there are classes on the images for styling (about/recent-works-fellows)
- Recent Work
- Books
- People Views
- Launch
- - CAS-180, CAS-181

CAS-180: trim and refine views, add classes

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_fellows.yml
package-lock.json

- Added a view for the case of Board of Directors (only full title)
- Now-ish
- Pretty important
1. Replace BoT page with new paragraph option
2. View that you don't see their academic discipline but DO see their titles
- JIRA ticket
- Other PRs

CAS-202: Fixup of view

---

docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_fellows.yml

- Fix duplication in jump menu for Board of Directors jump menu
- Now
- When possible
1. Go to the Board of Directors page
2. Look at the jump menu
- Just the one view!
- CAS-206

CAS-206: fix to jumpmenu

---

docroot/profiles/custom/stanford_profile/config/sync/field.field.node.stanford_person.su_casbs_person_bio.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_fellows.yml

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

casbs_person_bio Aggregation settings to entity ID

---

README.md

- This brings us up to Drupal 10.1.5
- Upstream changes integrated to get to stanford_profile `tags/11.1.3`
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

Drupal 10.1.6 and stanford_profile tags/11.0.9

---

composer.json
docroot/robots.txt
patches/robotstxt.patch

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

Added robots.txt patch

---

docroot/profiles/custom/stanford_profile/config/sync/core.extension.yml
docroot/profiles/custom/stanford_profile/config/sync/field.field.node.stanford_person.su_casbs_person_bio.yml
docroot/profiles/custom/stanford_profile/config/sync/views.view.casbs_current_fellows.yml

[modify current fellows view try again]
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

modify current fellows view try again
